name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install Dependencies
      run: poetry install --without dev
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Upload coverage
      uses: codecov/codecov-action@v1
